### ISSUE TITLE
Newest version of thermal expansion/redstone arsenal incompatibility

### ISSUE THREAD

**Issue by Staegrin** [smbarbour/Reconstructor#4]
So with the release of thermal dynamics all the other mods from the cofh team got updated as well.
Now the reconstructor is no longer compatible and gives an error when starting minecraft. Thought I should notify you.

crash log:
http://pastebin.com/3Yt83buQ

**Comment by smbarbour** [comment]
This was fixed in Reconstructor 2.1, but I have not yet tested all of the changes that were made for 2.1.

**Comment by Manuepolis23** [comment]
please release this as soon as posible

**Comment by smbarbour** [comment]
It is released.
